/*
 * vcverifier
 *
 * Backend component to verify credentials
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CredentialSchema struct {

	Id string `json:"id,omitempty"`

	Type string `json:"type,omitempty"`
}
