/*
 * vcverifier
 *
 * Backend component to verify credentials
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SubjectRole struct {

	Names []string `json:"names,omitempty"`

	Target string `json:"target,omitempty"`
}
