/*
 * vcverifier
 *
 * Backend component to verify credentials
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ErrorMessage struct {

	Summary string `json:"summary,omitempty"`

	Details string `json:"details,omitempty"`
}
