/*
 * vcverifier
 *
 * Backend component to verify credentials
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Jwk struct {

	Kid string `json:"kid,omitempty"`

	Kty string `json:"kty,omitempty"`

	Use string `json:"use,omitempty"`

	Alg string `json:"alg,omitempty"`

	Crv string `json:"crv,omitempty"`

	X string `json:"x,omitempty"`

	Y string `json:"y,omitempty"`

	N string `json:"n,omitempty"`

	E string `json:"e,omitempty"`

	D string `json:"d,omitempty"`
}
