/*
 * Authorisation API
 *
 * The subset of the [Authentication API as defined by EBSI](https://api-pilot.ebsi.eu/docs/apis/authorisation/latest#/). 
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package openapi

type TokenRequestBody struct {
	// MUST be set to \"vp_token\"
	GrantType string `json:"grant_type"`
	// Signed Verifiable Presentation. See also the VP Token schema definition.
	VpToken string `json:"vp_token"`
	// Descriptor for the vp_token, linked by presentation_definition. See also the Presentation Definition schema.
	PresentationSubmission string `json:"presentation_submission"`
	// OIDC scope
	Scope string `json:"scope"`
}
