// Code generated by ent, DO NOT EDIT.

package publickey

import (
	"time"
)

const (
	// Label holds the string label denoting the publickey type in the database.
	Label = "public_key"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldKty holds the string denoting the kty field in the database.
	FieldKty = "kty"
	// FieldAlg holds the string denoting the alg field in the database.
	FieldAlg = "alg"
	// FieldJwk holds the string denoting the jwk field in the database.
	FieldJwk = "jwk"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the publickey in the database.
	Table = "public_keys"
)

// Columns holds all SQL columns for publickey fields.
var Columns = []string{
	FieldID,
	FieldKty,
	FieldAlg,
	FieldJwk,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
)
