// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CredentialsColumns holds the columns for the "credentials" table.
	CredentialsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "type", Type: field.TypeString, Default: "jwt_vc"},
		{Name: "raw", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "natural_person_credentials", Type: field.TypeString, Nullable: true},
		{Name: "user_credentials", Type: field.TypeString, Nullable: true},
	}
	// CredentialsTable holds the schema information for the "credentials" table.
	CredentialsTable = &schema.Table{
		Name:       "credentials",
		Columns:    CredentialsColumns,
		PrimaryKey: []*schema.Column{CredentialsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "credentials_natural_persons_credentials",
				Columns:    []*schema.Column{CredentialsColumns[5]},
				RefColumns: []*schema.Column{NaturalPersonsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "credentials_users_credentials",
				Columns:    []*schema.Column{CredentialsColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// DiDsColumns holds the columns for the "di_ds" table.
	DiDsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "method", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_dids", Type: field.TypeString, Nullable: true},
	}
	// DiDsTable holds the schema information for the "di_ds" table.
	DiDsTable = &schema.Table{
		Name:       "di_ds",
		Columns:    DiDsColumns,
		PrimaryKey: []*schema.Column{DiDsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "di_ds_users_dids",
				Columns:    []*schema.Column{DiDsColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// NaturalPersonsColumns holds the columns for the "natural_persons" table.
	NaturalPersonsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "displayname", Type: field.TypeString, Nullable: true},
		{Name: "type", Type: field.TypeString},
		{Name: "password", Type: field.TypeBytes},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// NaturalPersonsTable holds the schema information for the "natural_persons" table.
	NaturalPersonsTable = &schema.Table{
		Name:       "natural_persons",
		Columns:    NaturalPersonsColumns,
		PrimaryKey: []*schema.Column{NaturalPersonsColumns[0]},
	}
	// PrivateKeysColumns holds the columns for the "private_keys" table.
	PrivateKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "kty", Type: field.TypeString},
		{Name: "alg", Type: field.TypeString, Nullable: true},
		{Name: "jwk", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "natural_person_keys", Type: field.TypeString, Nullable: true},
		{Name: "user_keys", Type: field.TypeString, Nullable: true},
	}
	// PrivateKeysTable holds the schema information for the "private_keys" table.
	PrivateKeysTable = &schema.Table{
		Name:       "private_keys",
		Columns:    PrivateKeysColumns,
		PrimaryKey: []*schema.Column{PrivateKeysColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "private_keys_natural_persons_keys",
				Columns:    []*schema.Column{PrivateKeysColumns[6]},
				RefColumns: []*schema.Column{NaturalPersonsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "private_keys_users_keys",
				Columns:    []*schema.Column{PrivateKeysColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// PublicKeysColumns holds the columns for the "public_keys" table.
	PublicKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "kty", Type: field.TypeString},
		{Name: "alg", Type: field.TypeString, Nullable: true},
		{Name: "jwk", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// PublicKeysTable holds the schema information for the "public_keys" table.
	PublicKeysTable = &schema.Table{
		Name:       "public_keys",
		Columns:    PublicKeysColumns,
		PrimaryKey: []*schema.Column{PublicKeysColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "displayname", Type: field.TypeString, Nullable: true},
		{Name: "type", Type: field.TypeString},
		{Name: "password", Type: field.TypeBytes},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CredentialsTable,
		DiDsTable,
		NaturalPersonsTable,
		PrivateKeysTable,
		PublicKeysTable,
		UsersTable,
	}
)

func init() {
	CredentialsTable.ForeignKeys[0].RefTable = NaturalPersonsTable
	CredentialsTable.ForeignKeys[1].RefTable = UsersTable
	DiDsTable.ForeignKeys[0].RefTable = UsersTable
	PrivateKeysTable.ForeignKeys[0].RefTable = NaturalPersonsTable
	PrivateKeysTable.ForeignKeys[1].RefTable = UsersTable
}
