/*
 * DID Registry
 *
 * The subset of the [DID Registry as defined by EBSI](https://api-pilot.ebsi.eu/docs/apis/did-registry/v4#/) as currently required by the [VCVerifier](https://github.com/FIWARE/VCVerifier). 
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package tir

type JsonWebKey2020VerificationMethod struct {
	Id string `json:"id,omitempty"`
	Type_ string `json:"type,omitempty"`
	Controller string `json:"controller,omitempty"`
	PublicKeyJWK *Jwk `json:"publicKeyJWK,omitempty"`
}
