/*
 * DID Registry
 *
 * The subset of the [DID Registry as defined by EBSI](https://api-pilot.ebsi.eu/docs/apis/did-registry/v4#/) as currently required by the [VCVerifier](https://github.com/FIWARE/VCVerifier). 
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package tir

type Jwk struct {
	Alg string `json:"alg,omitempty"`
	Kty string `json:"kty,omitempty"`
	Kid string `json:"kid,omitempty"`
	N string `json:"n,omitempty"`
	E string `json:"e,omitempty"`
	X5u string `json:"x5u,omitempty"`
	Use string `json:"use,omitempty"`
}
