// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/fiware/vcbackend/ent/migrate"

	"github.com/fiware/vcbackend/ent/credential"
	"github.com/fiware/vcbackend/ent/did"
	"github.com/fiware/vcbackend/ent/naturalperson"
	"github.com/fiware/vcbackend/ent/privatekey"
	"github.com/fiware/vcbackend/ent/publickey"
	"github.com/fiware/vcbackend/ent/user"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Credential is the client for interacting with the Credential builders.
	Credential *CredentialClient
	// DID is the client for interacting with the DID builders.
	DID *DIDClient
	// NaturalPerson is the client for interacting with the NaturalPerson builders.
	NaturalPerson *NaturalPersonClient
	// PrivateKey is the client for interacting with the PrivateKey builders.
	PrivateKey *PrivateKeyClient
	// PublicKey is the client for interacting with the PublicKey builders.
	PublicKey *PublicKeyClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Credential = NewCredentialClient(c.config)
	c.DID = NewDIDClient(c.config)
	c.NaturalPerson = NewNaturalPersonClient(c.config)
	c.PrivateKey = NewPrivateKeyClient(c.config)
	c.PublicKey = NewPublicKeyClient(c.config)
	c.User = NewUserClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		Credential:    NewCredentialClient(cfg),
		DID:           NewDIDClient(cfg),
		NaturalPerson: NewNaturalPersonClient(cfg),
		PrivateKey:    NewPrivateKeyClient(cfg),
		PublicKey:     NewPublicKeyClient(cfg),
		User:          NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		Credential:    NewCredentialClient(cfg),
		DID:           NewDIDClient(cfg),
		NaturalPerson: NewNaturalPersonClient(cfg),
		PrivateKey:    NewPrivateKeyClient(cfg),
		PublicKey:     NewPublicKeyClient(cfg),
		User:          NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Credential.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Credential.Use(hooks...)
	c.DID.Use(hooks...)
	c.NaturalPerson.Use(hooks...)
	c.PrivateKey.Use(hooks...)
	c.PublicKey.Use(hooks...)
	c.User.Use(hooks...)
}

// CredentialClient is a client for the Credential schema.
type CredentialClient struct {
	config
}

// NewCredentialClient returns a client for the Credential from the given config.
func NewCredentialClient(c config) *CredentialClient {
	return &CredentialClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `credential.Hooks(f(g(h())))`.
func (c *CredentialClient) Use(hooks ...Hook) {
	c.hooks.Credential = append(c.hooks.Credential, hooks...)
}

// Create returns a builder for creating a Credential entity.
func (c *CredentialClient) Create() *CredentialCreate {
	mutation := newCredentialMutation(c.config, OpCreate)
	return &CredentialCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Credential entities.
func (c *CredentialClient) CreateBulk(builders ...*CredentialCreate) *CredentialCreateBulk {
	return &CredentialCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Credential.
func (c *CredentialClient) Update() *CredentialUpdate {
	mutation := newCredentialMutation(c.config, OpUpdate)
	return &CredentialUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CredentialClient) UpdateOne(cr *Credential) *CredentialUpdateOne {
	mutation := newCredentialMutation(c.config, OpUpdateOne, withCredential(cr))
	return &CredentialUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CredentialClient) UpdateOneID(id string) *CredentialUpdateOne {
	mutation := newCredentialMutation(c.config, OpUpdateOne, withCredentialID(id))
	return &CredentialUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Credential.
func (c *CredentialClient) Delete() *CredentialDelete {
	mutation := newCredentialMutation(c.config, OpDelete)
	return &CredentialDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CredentialClient) DeleteOne(cr *Credential) *CredentialDeleteOne {
	return c.DeleteOneID(cr.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *CredentialClient) DeleteOneID(id string) *CredentialDeleteOne {
	builder := c.Delete().Where(credential.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CredentialDeleteOne{builder}
}

// Query returns a query builder for Credential.
func (c *CredentialClient) Query() *CredentialQuery {
	return &CredentialQuery{
		config: c.config,
	}
}

// Get returns a Credential entity by its id.
func (c *CredentialClient) Get(ctx context.Context, id string) (*Credential, error) {
	return c.Query().Where(credential.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CredentialClient) GetX(ctx context.Context, id string) *Credential {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryAccount queries the account edge of a Credential.
func (c *CredentialClient) QueryAccount(cr *Credential) *UserQuery {
	query := &UserQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := cr.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(credential.Table, credential.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, credential.AccountTable, credential.AccountColumn),
		)
		fromV = sqlgraph.Neighbors(cr.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CredentialClient) Hooks() []Hook {
	return c.hooks.Credential
}

// DIDClient is a client for the DID schema.
type DIDClient struct {
	config
}

// NewDIDClient returns a client for the DID from the given config.
func NewDIDClient(c config) *DIDClient {
	return &DIDClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `did.Hooks(f(g(h())))`.
func (c *DIDClient) Use(hooks ...Hook) {
	c.hooks.DID = append(c.hooks.DID, hooks...)
}

// Create returns a builder for creating a DID entity.
func (c *DIDClient) Create() *DIDCreate {
	mutation := newDIDMutation(c.config, OpCreate)
	return &DIDCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DID entities.
func (c *DIDClient) CreateBulk(builders ...*DIDCreate) *DIDCreateBulk {
	return &DIDCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DID.
func (c *DIDClient) Update() *DIDUpdate {
	mutation := newDIDMutation(c.config, OpUpdate)
	return &DIDUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DIDClient) UpdateOne(d *DID) *DIDUpdateOne {
	mutation := newDIDMutation(c.config, OpUpdateOne, withDID(d))
	return &DIDUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DIDClient) UpdateOneID(id string) *DIDUpdateOne {
	mutation := newDIDMutation(c.config, OpUpdateOne, withDIDID(id))
	return &DIDUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DID.
func (c *DIDClient) Delete() *DIDDelete {
	mutation := newDIDMutation(c.config, OpDelete)
	return &DIDDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DIDClient) DeleteOne(d *DID) *DIDDeleteOne {
	return c.DeleteOneID(d.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *DIDClient) DeleteOneID(id string) *DIDDeleteOne {
	builder := c.Delete().Where(did.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DIDDeleteOne{builder}
}

// Query returns a query builder for DID.
func (c *DIDClient) Query() *DIDQuery {
	return &DIDQuery{
		config: c.config,
	}
}

// Get returns a DID entity by its id.
func (c *DIDClient) Get(ctx context.Context, id string) (*DID, error) {
	return c.Query().Where(did.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DIDClient) GetX(ctx context.Context, id string) *DID {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a DID.
func (c *DIDClient) QueryUser(d *DID) *UserQuery {
	query := &UserQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := d.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(did.Table, did.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, did.UserTable, did.UserColumn),
		)
		fromV = sqlgraph.Neighbors(d.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *DIDClient) Hooks() []Hook {
	return c.hooks.DID
}

// NaturalPersonClient is a client for the NaturalPerson schema.
type NaturalPersonClient struct {
	config
}

// NewNaturalPersonClient returns a client for the NaturalPerson from the given config.
func NewNaturalPersonClient(c config) *NaturalPersonClient {
	return &NaturalPersonClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `naturalperson.Hooks(f(g(h())))`.
func (c *NaturalPersonClient) Use(hooks ...Hook) {
	c.hooks.NaturalPerson = append(c.hooks.NaturalPerson, hooks...)
}

// Create returns a builder for creating a NaturalPerson entity.
func (c *NaturalPersonClient) Create() *NaturalPersonCreate {
	mutation := newNaturalPersonMutation(c.config, OpCreate)
	return &NaturalPersonCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of NaturalPerson entities.
func (c *NaturalPersonClient) CreateBulk(builders ...*NaturalPersonCreate) *NaturalPersonCreateBulk {
	return &NaturalPersonCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for NaturalPerson.
func (c *NaturalPersonClient) Update() *NaturalPersonUpdate {
	mutation := newNaturalPersonMutation(c.config, OpUpdate)
	return &NaturalPersonUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *NaturalPersonClient) UpdateOne(np *NaturalPerson) *NaturalPersonUpdateOne {
	mutation := newNaturalPersonMutation(c.config, OpUpdateOne, withNaturalPerson(np))
	return &NaturalPersonUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *NaturalPersonClient) UpdateOneID(id string) *NaturalPersonUpdateOne {
	mutation := newNaturalPersonMutation(c.config, OpUpdateOne, withNaturalPersonID(id))
	return &NaturalPersonUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for NaturalPerson.
func (c *NaturalPersonClient) Delete() *NaturalPersonDelete {
	mutation := newNaturalPersonMutation(c.config, OpDelete)
	return &NaturalPersonDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *NaturalPersonClient) DeleteOne(np *NaturalPerson) *NaturalPersonDeleteOne {
	return c.DeleteOneID(np.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *NaturalPersonClient) DeleteOneID(id string) *NaturalPersonDeleteOne {
	builder := c.Delete().Where(naturalperson.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &NaturalPersonDeleteOne{builder}
}

// Query returns a query builder for NaturalPerson.
func (c *NaturalPersonClient) Query() *NaturalPersonQuery {
	return &NaturalPersonQuery{
		config: c.config,
	}
}

// Get returns a NaturalPerson entity by its id.
func (c *NaturalPersonClient) Get(ctx context.Context, id string) (*NaturalPerson, error) {
	return c.Query().Where(naturalperson.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *NaturalPersonClient) GetX(ctx context.Context, id string) *NaturalPerson {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryKeys queries the keys edge of a NaturalPerson.
func (c *NaturalPersonClient) QueryKeys(np *NaturalPerson) *PrivateKeyQuery {
	query := &PrivateKeyQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := np.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(naturalperson.Table, naturalperson.FieldID, id),
			sqlgraph.To(privatekey.Table, privatekey.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, naturalperson.KeysTable, naturalperson.KeysColumn),
		)
		fromV = sqlgraph.Neighbors(np.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryCredentials queries the credentials edge of a NaturalPerson.
func (c *NaturalPersonClient) QueryCredentials(np *NaturalPerson) *CredentialQuery {
	query := &CredentialQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := np.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(naturalperson.Table, naturalperson.FieldID, id),
			sqlgraph.To(credential.Table, credential.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, naturalperson.CredentialsTable, naturalperson.CredentialsColumn),
		)
		fromV = sqlgraph.Neighbors(np.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *NaturalPersonClient) Hooks() []Hook {
	return c.hooks.NaturalPerson
}

// PrivateKeyClient is a client for the PrivateKey schema.
type PrivateKeyClient struct {
	config
}

// NewPrivateKeyClient returns a client for the PrivateKey from the given config.
func NewPrivateKeyClient(c config) *PrivateKeyClient {
	return &PrivateKeyClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `privatekey.Hooks(f(g(h())))`.
func (c *PrivateKeyClient) Use(hooks ...Hook) {
	c.hooks.PrivateKey = append(c.hooks.PrivateKey, hooks...)
}

// Create returns a builder for creating a PrivateKey entity.
func (c *PrivateKeyClient) Create() *PrivateKeyCreate {
	mutation := newPrivateKeyMutation(c.config, OpCreate)
	return &PrivateKeyCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PrivateKey entities.
func (c *PrivateKeyClient) CreateBulk(builders ...*PrivateKeyCreate) *PrivateKeyCreateBulk {
	return &PrivateKeyCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PrivateKey.
func (c *PrivateKeyClient) Update() *PrivateKeyUpdate {
	mutation := newPrivateKeyMutation(c.config, OpUpdate)
	return &PrivateKeyUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PrivateKeyClient) UpdateOne(pk *PrivateKey) *PrivateKeyUpdateOne {
	mutation := newPrivateKeyMutation(c.config, OpUpdateOne, withPrivateKey(pk))
	return &PrivateKeyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PrivateKeyClient) UpdateOneID(id string) *PrivateKeyUpdateOne {
	mutation := newPrivateKeyMutation(c.config, OpUpdateOne, withPrivateKeyID(id))
	return &PrivateKeyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PrivateKey.
func (c *PrivateKeyClient) Delete() *PrivateKeyDelete {
	mutation := newPrivateKeyMutation(c.config, OpDelete)
	return &PrivateKeyDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PrivateKeyClient) DeleteOne(pk *PrivateKey) *PrivateKeyDeleteOne {
	return c.DeleteOneID(pk.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *PrivateKeyClient) DeleteOneID(id string) *PrivateKeyDeleteOne {
	builder := c.Delete().Where(privatekey.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PrivateKeyDeleteOne{builder}
}

// Query returns a query builder for PrivateKey.
func (c *PrivateKeyClient) Query() *PrivateKeyQuery {
	return &PrivateKeyQuery{
		config: c.config,
	}
}

// Get returns a PrivateKey entity by its id.
func (c *PrivateKeyClient) Get(ctx context.Context, id string) (*PrivateKey, error) {
	return c.Query().Where(privatekey.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PrivateKeyClient) GetX(ctx context.Context, id string) *PrivateKey {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a PrivateKey.
func (c *PrivateKeyClient) QueryUser(pk *PrivateKey) *UserQuery {
	query := &UserQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := pk.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(privatekey.Table, privatekey.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, privatekey.UserTable, privatekey.UserColumn),
		)
		fromV = sqlgraph.Neighbors(pk.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PrivateKeyClient) Hooks() []Hook {
	return c.hooks.PrivateKey
}

// PublicKeyClient is a client for the PublicKey schema.
type PublicKeyClient struct {
	config
}

// NewPublicKeyClient returns a client for the PublicKey from the given config.
func NewPublicKeyClient(c config) *PublicKeyClient {
	return &PublicKeyClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `publickey.Hooks(f(g(h())))`.
func (c *PublicKeyClient) Use(hooks ...Hook) {
	c.hooks.PublicKey = append(c.hooks.PublicKey, hooks...)
}

// Create returns a builder for creating a PublicKey entity.
func (c *PublicKeyClient) Create() *PublicKeyCreate {
	mutation := newPublicKeyMutation(c.config, OpCreate)
	return &PublicKeyCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PublicKey entities.
func (c *PublicKeyClient) CreateBulk(builders ...*PublicKeyCreate) *PublicKeyCreateBulk {
	return &PublicKeyCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PublicKey.
func (c *PublicKeyClient) Update() *PublicKeyUpdate {
	mutation := newPublicKeyMutation(c.config, OpUpdate)
	return &PublicKeyUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PublicKeyClient) UpdateOne(pk *PublicKey) *PublicKeyUpdateOne {
	mutation := newPublicKeyMutation(c.config, OpUpdateOne, withPublicKey(pk))
	return &PublicKeyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PublicKeyClient) UpdateOneID(id string) *PublicKeyUpdateOne {
	mutation := newPublicKeyMutation(c.config, OpUpdateOne, withPublicKeyID(id))
	return &PublicKeyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PublicKey.
func (c *PublicKeyClient) Delete() *PublicKeyDelete {
	mutation := newPublicKeyMutation(c.config, OpDelete)
	return &PublicKeyDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PublicKeyClient) DeleteOne(pk *PublicKey) *PublicKeyDeleteOne {
	return c.DeleteOneID(pk.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *PublicKeyClient) DeleteOneID(id string) *PublicKeyDeleteOne {
	builder := c.Delete().Where(publickey.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PublicKeyDeleteOne{builder}
}

// Query returns a query builder for PublicKey.
func (c *PublicKeyClient) Query() *PublicKeyQuery {
	return &PublicKeyQuery{
		config: c.config,
	}
}

// Get returns a PublicKey entity by its id.
func (c *PublicKeyClient) Get(ctx context.Context, id string) (*PublicKey, error) {
	return c.Query().Where(publickey.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PublicKeyClient) GetX(ctx context.Context, id string) *PublicKey {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PublicKeyClient) Hooks() []Hook {
	return c.hooks.PublicKey
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(u *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(u))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id string) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(u *User) *UserDeleteOne {
	return c.DeleteOneID(u.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id string) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id string) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id string) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryKeys queries the keys edge of a User.
func (c *UserClient) QueryKeys(u *User) *PrivateKeyQuery {
	query := &PrivateKeyQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(privatekey.Table, privatekey.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.KeysTable, user.KeysColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryDids queries the dids edge of a User.
func (c *UserClient) QueryDids(u *User) *DIDQuery {
	query := &DIDQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(did.Table, did.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.DidsTable, user.DidsColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryCredentials queries the credentials edge of a User.
func (c *UserClient) QueryCredentials(u *User) *CredentialQuery {
	query := &CredentialQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(credential.Table, credential.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.CredentialsTable, user.CredentialsColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}
