// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fiware/vcbackend/ent/predicate"
	"github.com/fiware/vcbackend/ent/privatekey"
)

// PrivateKeyDelete is the builder for deleting a PrivateKey entity.
type PrivateKeyDelete struct {
	config
	hooks    []Hook
	mutation *PrivateKeyMutation
}

// Where appends a list predicates to the PrivateKeyDelete builder.
func (pkd *PrivateKeyDelete) Where(ps ...predicate.PrivateKey) *PrivateKeyDelete {
	pkd.mutation.Where(ps...)
	return pkd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pkd *PrivateKeyDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(pkd.hooks) == 0 {
		affected, err = pkd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PrivateKeyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pkd.mutation = mutation
			affected, err = pkd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pkd.hooks) - 1; i >= 0; i-- {
			if pkd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pkd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pkd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (pkd *PrivateKeyDelete) ExecX(ctx context.Context) int {
	n, err := pkd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pkd *PrivateKeyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: privatekey.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: privatekey.FieldID,
			},
		},
	}
	if ps := pkd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pkd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// PrivateKeyDeleteOne is the builder for deleting a single PrivateKey entity.
type PrivateKeyDeleteOne struct {
	pkd *PrivateKeyDelete
}

// Exec executes the deletion query.
func (pkdo *PrivateKeyDeleteOne) Exec(ctx context.Context) error {
	n, err := pkdo.pkd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{privatekey.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pkdo *PrivateKeyDeleteOne) ExecX(ctx context.Context) {
	pkdo.pkd.ExecX(ctx)
}
