// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fiware/vcbackend/ent/predicate"
	"github.com/fiware/vcbackend/ent/publickey"
)

// PublicKeyUpdate is the builder for updating PublicKey entities.
type PublicKeyUpdate struct {
	config
	hooks    []Hook
	mutation *PublicKeyMutation
}

// Where appends a list predicates to the PublicKeyUpdate builder.
func (pku *PublicKeyUpdate) Where(ps ...predicate.PublicKey) *PublicKeyUpdate {
	pku.mutation.Where(ps...)
	return pku
}

// SetKty sets the "kty" field.
func (pku *PublicKeyUpdate) SetKty(s string) *PublicKeyUpdate {
	pku.mutation.SetKty(s)
	return pku
}

// SetAlg sets the "alg" field.
func (pku *PublicKeyUpdate) SetAlg(s string) *PublicKeyUpdate {
	pku.mutation.SetAlg(s)
	return pku
}

// SetNillableAlg sets the "alg" field if the given value is not nil.
func (pku *PublicKeyUpdate) SetNillableAlg(s *string) *PublicKeyUpdate {
	if s != nil {
		pku.SetAlg(*s)
	}
	return pku
}

// ClearAlg clears the value of the "alg" field.
func (pku *PublicKeyUpdate) ClearAlg() *PublicKeyUpdate {
	pku.mutation.ClearAlg()
	return pku
}

// SetJwk sets the "jwk" field.
func (pku *PublicKeyUpdate) SetJwk(u []uint8) *PublicKeyUpdate {
	pku.mutation.SetJwk(u)
	return pku
}

// SetUpdatedAt sets the "updated_at" field.
func (pku *PublicKeyUpdate) SetUpdatedAt(t time.Time) *PublicKeyUpdate {
	pku.mutation.SetUpdatedAt(t)
	return pku
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (pku *PublicKeyUpdate) SetNillableUpdatedAt(t *time.Time) *PublicKeyUpdate {
	if t != nil {
		pku.SetUpdatedAt(*t)
	}
	return pku
}

// Mutation returns the PublicKeyMutation object of the builder.
func (pku *PublicKeyUpdate) Mutation() *PublicKeyMutation {
	return pku.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pku *PublicKeyUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(pku.hooks) == 0 {
		affected, err = pku.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PublicKeyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pku.mutation = mutation
			affected, err = pku.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pku.hooks) - 1; i >= 0; i-- {
			if pku.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pku.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pku.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (pku *PublicKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := pku.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pku *PublicKeyUpdate) Exec(ctx context.Context) error {
	_, err := pku.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pku *PublicKeyUpdate) ExecX(ctx context.Context) {
	if err := pku.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pku *PublicKeyUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   publickey.Table,
			Columns: publickey.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: publickey.FieldID,
			},
		},
	}
	if ps := pku.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pku.mutation.Kty(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: publickey.FieldKty,
		})
	}
	if value, ok := pku.mutation.Alg(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: publickey.FieldAlg,
		})
	}
	if pku.mutation.AlgCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: publickey.FieldAlg,
		})
	}
	if value, ok := pku.mutation.Jwk(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: publickey.FieldJwk,
		})
	}
	if value, ok := pku.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: publickey.FieldUpdatedAt,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pku.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{publickey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// PublicKeyUpdateOne is the builder for updating a single PublicKey entity.
type PublicKeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PublicKeyMutation
}

// SetKty sets the "kty" field.
func (pkuo *PublicKeyUpdateOne) SetKty(s string) *PublicKeyUpdateOne {
	pkuo.mutation.SetKty(s)
	return pkuo
}

// SetAlg sets the "alg" field.
func (pkuo *PublicKeyUpdateOne) SetAlg(s string) *PublicKeyUpdateOne {
	pkuo.mutation.SetAlg(s)
	return pkuo
}

// SetNillableAlg sets the "alg" field if the given value is not nil.
func (pkuo *PublicKeyUpdateOne) SetNillableAlg(s *string) *PublicKeyUpdateOne {
	if s != nil {
		pkuo.SetAlg(*s)
	}
	return pkuo
}

// ClearAlg clears the value of the "alg" field.
func (pkuo *PublicKeyUpdateOne) ClearAlg() *PublicKeyUpdateOne {
	pkuo.mutation.ClearAlg()
	return pkuo
}

// SetJwk sets the "jwk" field.
func (pkuo *PublicKeyUpdateOne) SetJwk(u []uint8) *PublicKeyUpdateOne {
	pkuo.mutation.SetJwk(u)
	return pkuo
}

// SetUpdatedAt sets the "updated_at" field.
func (pkuo *PublicKeyUpdateOne) SetUpdatedAt(t time.Time) *PublicKeyUpdateOne {
	pkuo.mutation.SetUpdatedAt(t)
	return pkuo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (pkuo *PublicKeyUpdateOne) SetNillableUpdatedAt(t *time.Time) *PublicKeyUpdateOne {
	if t != nil {
		pkuo.SetUpdatedAt(*t)
	}
	return pkuo
}

// Mutation returns the PublicKeyMutation object of the builder.
func (pkuo *PublicKeyUpdateOne) Mutation() *PublicKeyMutation {
	return pkuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (pkuo *PublicKeyUpdateOne) Select(field string, fields ...string) *PublicKeyUpdateOne {
	pkuo.fields = append([]string{field}, fields...)
	return pkuo
}

// Save executes the query and returns the updated PublicKey entity.
func (pkuo *PublicKeyUpdateOne) Save(ctx context.Context) (*PublicKey, error) {
	var (
		err  error
		node *PublicKey
	)
	if len(pkuo.hooks) == 0 {
		node, err = pkuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PublicKeyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pkuo.mutation = mutation
			node, err = pkuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(pkuo.hooks) - 1; i >= 0; i-- {
			if pkuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pkuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, pkuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*PublicKey)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from PublicKeyMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (pkuo *PublicKeyUpdateOne) SaveX(ctx context.Context) *PublicKey {
	node, err := pkuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (pkuo *PublicKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := pkuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pkuo *PublicKeyUpdateOne) ExecX(ctx context.Context) {
	if err := pkuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pkuo *PublicKeyUpdateOne) sqlSave(ctx context.Context) (_node *PublicKey, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   publickey.Table,
			Columns: publickey.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: publickey.FieldID,
			},
		},
	}
	id, ok := pkuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PublicKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := pkuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, publickey.FieldID)
		for _, f := range fields {
			if !publickey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != publickey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := pkuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pkuo.mutation.Kty(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: publickey.FieldKty,
		})
	}
	if value, ok := pkuo.mutation.Alg(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: publickey.FieldAlg,
		})
	}
	if pkuo.mutation.AlgCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: publickey.FieldAlg,
		})
	}
	if value, ok := pkuo.mutation.Jwk(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: publickey.FieldJwk,
		})
	}
	if value, ok := pkuo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: publickey.FieldUpdatedAt,
		})
	}
	_node = &PublicKey{config: pkuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, pkuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{publickey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
