// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/fiware/vcbackend/ent/credential"
	"github.com/fiware/vcbackend/ent/did"
	"github.com/fiware/vcbackend/ent/naturalperson"
	"github.com/fiware/vcbackend/ent/privatekey"
	"github.com/fiware/vcbackend/ent/publickey"
	"github.com/fiware/vcbackend/ent/schema"
	"github.com/fiware/vcbackend/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	credentialFields := schema.Credential{}.Fields()
	_ = credentialFields
	// credentialDescType is the schema descriptor for type field.
	credentialDescType := credentialFields[1].Descriptor()
	// credential.DefaultType holds the default value on creation for the type field.
	credential.DefaultType = credentialDescType.Default.(string)
	// credentialDescCreatedAt is the schema descriptor for created_at field.
	credentialDescCreatedAt := credentialFields[3].Descriptor()
	// credential.DefaultCreatedAt holds the default value on creation for the created_at field.
	credential.DefaultCreatedAt = credentialDescCreatedAt.Default.(func() time.Time)
	// credentialDescUpdatedAt is the schema descriptor for updated_at field.
	credentialDescUpdatedAt := credentialFields[4].Descriptor()
	// credential.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	credential.DefaultUpdatedAt = credentialDescUpdatedAt.Default.(func() time.Time)
	didFields := schema.DID{}.Fields()
	_ = didFields
	// didDescCreatedAt is the schema descriptor for created_at field.
	didDescCreatedAt := didFields[2].Descriptor()
	// did.DefaultCreatedAt holds the default value on creation for the created_at field.
	did.DefaultCreatedAt = didDescCreatedAt.Default.(func() time.Time)
	// didDescUpdatedAt is the schema descriptor for updated_at field.
	didDescUpdatedAt := didFields[3].Descriptor()
	// did.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	did.DefaultUpdatedAt = didDescUpdatedAt.Default.(func() time.Time)
	naturalpersonFields := schema.NaturalPerson{}.Fields()
	_ = naturalpersonFields
	// naturalpersonDescName is the schema descriptor for name field.
	naturalpersonDescName := naturalpersonFields[1].Descriptor()
	// naturalperson.NameValidator is a validator for the "name" field. It is called by the builders before save.
	naturalperson.NameValidator = naturalpersonDescName.Validators[0].(func(string) error)
	// naturalpersonDescType is the schema descriptor for type field.
	naturalpersonDescType := naturalpersonFields[3].Descriptor()
	// naturalperson.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	naturalperson.TypeValidator = naturalpersonDescType.Validators[0].(func(string) error)
	// naturalpersonDescPassword is the schema descriptor for password field.
	naturalpersonDescPassword := naturalpersonFields[4].Descriptor()
	// naturalperson.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	naturalperson.PasswordValidator = naturalpersonDescPassword.Validators[0].(func([]byte) error)
	// naturalpersonDescCreatedAt is the schema descriptor for created_at field.
	naturalpersonDescCreatedAt := naturalpersonFields[5].Descriptor()
	// naturalperson.DefaultCreatedAt holds the default value on creation for the created_at field.
	naturalperson.DefaultCreatedAt = naturalpersonDescCreatedAt.Default.(func() time.Time)
	// naturalpersonDescUpdatedAt is the schema descriptor for updated_at field.
	naturalpersonDescUpdatedAt := naturalpersonFields[6].Descriptor()
	// naturalperson.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	naturalperson.DefaultUpdatedAt = naturalpersonDescUpdatedAt.Default.(func() time.Time)
	// naturalpersonDescID is the schema descriptor for id field.
	naturalpersonDescID := naturalpersonFields[0].Descriptor()
	// naturalperson.IDValidator is a validator for the "id" field. It is called by the builders before save.
	naturalperson.IDValidator = naturalpersonDescID.Validators[0].(func(string) error)
	privatekeyFields := schema.PrivateKey{}.Fields()
	_ = privatekeyFields
	// privatekeyDescCreatedAt is the schema descriptor for created_at field.
	privatekeyDescCreatedAt := privatekeyFields[4].Descriptor()
	// privatekey.DefaultCreatedAt holds the default value on creation for the created_at field.
	privatekey.DefaultCreatedAt = privatekeyDescCreatedAt.Default.(func() time.Time)
	// privatekeyDescUpdatedAt is the schema descriptor for updated_at field.
	privatekeyDescUpdatedAt := privatekeyFields[5].Descriptor()
	// privatekey.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	privatekey.DefaultUpdatedAt = privatekeyDescUpdatedAt.Default.(func() time.Time)
	publickeyFields := schema.PublicKey{}.Fields()
	_ = publickeyFields
	// publickeyDescCreatedAt is the schema descriptor for created_at field.
	publickeyDescCreatedAt := publickeyFields[4].Descriptor()
	// publickey.DefaultCreatedAt holds the default value on creation for the created_at field.
	publickey.DefaultCreatedAt = publickeyDescCreatedAt.Default.(func() time.Time)
	// publickeyDescUpdatedAt is the schema descriptor for updated_at field.
	publickeyDescUpdatedAt := publickeyFields[5].Descriptor()
	// publickey.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	publickey.DefaultUpdatedAt = publickeyDescUpdatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescType is the schema descriptor for type field.
	userDescType := userFields[3].Descriptor()
	// user.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	user.TypeValidator = userDescType.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[4].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func([]byte) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[6].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.IDValidator is a validator for the "id" field. It is called by the builders before save.
	user.IDValidator = userDescID.Validators[0].(func(string) error)
}
