// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Credential is the predicate function for credential builders.
type Credential func(*sql.Selector)

// DID is the predicate function for did builders.
type DID func(*sql.Selector)

// NaturalPerson is the predicate function for naturalperson builders.
type NaturalPerson func(*sql.Selector)

// PrivateKey is the predicate function for privatekey builders.
type PrivateKey func(*sql.Selector)

// PublicKey is the predicate function for publickey builders.
type PublicKey func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
